spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoservice
    username: postgres
    password: root
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

    hibernate:
      ddl-auto: create-drop

  liquibase:
    enabled: false